on: release
name: Build Release
jobs:
  azure-connector:
    name: azure blob utility
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: linux i386
      uses: Ayush900/go-release-executables@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: "386"
        GOOS: linux
        SUBDIR: "bnr-utils/nz_azConnector"
        EXECUTABLE_NAME: "nz_azConnector"
    - name: linux amd64
      uses: Ayush900/go-release-executables@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: amd64
        GOOS: linux
        SUBDIR: "bnr-utils/nz_azConnector"
        EXECUTABLE_NAME: "nz_azConnector"
    - name: windows amd64
      uses: Ayush900/go-release-executables@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: amd64
        GOOS: windows
        SUBDIR: "bnr-utils/nz_azConnector"
        EXECUTABLE_NAME: "nz_azConnector"
    - name: windows 386
      uses: Ayush900/go-release-executables@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: "386"
        GOOS: windows
        SUBDIR: "bnr-utils/nz_azConnector"
        EXECUTABLE_NAME: "nz_azConnector"
    - name: darwin amd64
      uses: Ayush900/go-release-executables@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: amd64
        GOOS: darwin
        SUBDIR: "bnr-utils/nz_azConnector"
        EXECUTABLE_NAME: "nz_azConnector"
    - name: darwin 386
      uses: Ayush900/go-release-executables@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: "386"
        GOOS: darwin
        SUBDIR: "bnr-utils/nz_azConnector"
        EXECUTABLE_NAME: "nz_azConnector"

  s3-connector:
    name: S3 connector linux amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use myrepo to build s3 connector
        uses: Ayush900/go-release-executables@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOARCH: amd64
          GOOS: linux
          SUBDIR: "bnr-utils/nz_s3Connector"
          EXECUTABLE_NAME: "nz_s3Connector"

      - name: Create tarball and upload release
        run: |
          tar -czf ../nz_s3connector.tgz -C bnr-utils/nz_s3connector .
          gh release upload ${{ github.event.release.tag_name }} ../nz_s3connector.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
