on: release
name: Build Release
jobs:
  # azure-connector:
  #   name: azure blob utility
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: linux i386
  #     uses: Ayush900/go-release-executables@v1.0.0
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       GOARCH: "386"
  #       GOOS: linux
  #       SUBDIR: "bnr-utils/nz_azConnector"
  #       EXECUTABLE_NAME: "nz_azConnector"
  # #   - name: linux amd64
  # #     uses: ibm/go-release-executables@v1.1.0
  # #     env:
  # #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # #       GOARCH: amd64
  # #       GOOS: linux
  # #       SUBDIR: "bnr-utils/nz_azConnector"
  # #       EXECUTABLE_NAME: "nz_azConnector"
  #   - name: windows amd64
  #     uses: Ayush900/go-release-executables@v1.0.0
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       GOARCH: amd64
  #       GOOS: windows
  #       SUBDIR: "bnr-utils/nz_azConnector"
  #       EXECUTABLE_NAME: "nz_azConnector"
  #   - name: windows 386
  #     uses: ibm/go-release-executables@v1.1.0
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       GOARCH: "386"
  #       GOOS: windows
  #       SUBDIR: "bnr-utils/nz_azConnector"
  #       EXECUTABLE_NAME: "nz_azConnector"
  #   - name: darwin amd64
  #     uses: ibm/go-release-executables@v1.1.0
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       GOARCH: amd64
  #       GOOS: darwin
  #       SUBDIR: "bnr-utils/nz_azConnector"
  #       EXECUTABLE_NAME: "nz_azConnector"
  #   - name: darwin 386
  #     uses: ibm/go-release-executables@v1.1.0
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       GOARCH: "386"
  #       GOOS: darwin
  #       SUBDIR: "bnr-utils/nz_azConnector"
  #       EXECUTABLE_NAME: "nz_azConnector"
  test:
    name: testrunbuild.sh
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Create tarball and upload release
          run: |
            echo "The value of THIS_GITHUB_EVENT : $THIS_GITHUB_EVENT"
            echo "The value of RELEASE_UPLOAD_URL : $RELEASE_UPLOAD_URL"
            echo "The value of RELEASE_TAG_NAME : $RELEASE_TAG_NAME"
            echo "The value of PROJECT_NAME : $PROJECT_NAME"
            cd go-release-executables           
            sudo bash main.sh
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GOARCH: "386"
            GOOS: darwin
            SUBDIR: "bnr-utils/nz_azConnector"
            EXECUTABLE_NAME: "nz_azConnector"

  as3-connector:
    name: S3 connector linux amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create tarball and upload release
        run: |
          THIS_GITHUB_EVENT=$(cat $GITHUB_EVENT_PATH)
          RELEASE_UPLOAD_URL=$(echo $THIS_GITHUB_EVENT | jq -r .release.upload_url)
          RELEASE_UPLOAD_URL=${RELEASE_UPLOAD_URL/\{?name,label\}/}
          RELEASE_TAG_NAME=$(echo $THIS_GITHUB_EVENT | jq -r .release.tag_name)
          PROJECT_NAME=$(basename $GITHUB_REPOSITORY)
          echo "The value of THIS_GITHUB_EVENT : $THIS_GITHUB_EVENT"
          echo "The value of RELEASE_UPLOAD_URL : $RELEASE_UPLOAD_URL"
          echo "The value of RELEASE_TAG_NAME : $RELEASE_TAG_NAME"
          echo "The value of PROJECT_NAME : $PROJECT_NAME"
          
          tar -czf bnr-utils/nz_s3connector.tgz -C bnr-utils/nz_s3Connector .
          gh release upload ${{ github.event.release.tag_name }} bnr-utils/nz_s3connector.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
